openapi: 3.0.1
servers:
  - description: Index swagger
    #url local
    url: https://localhost:8080

    #url produccion
    #url: https://api.samtel.co

info:
  description: Servicio de entidad Usuario.
  version: 0.0.1
  title: Usuarios
  contact:
    name: Samtel
    url: https://www.samtel.co/
    email: api@samtel.co
  license:
    name: GNU GPLv3
    url: ‘https://www.gnu.org/licenses/gpl-3.0.html’
tags:
  - name: Usuarios
    description: Gestion de usuarios

#----------------------------
#Endpoints de la Entidad
#----------------------------
#POST - CREAR USUARIO
paths:
  /v1/es/crearUsuario:
    post:
      tags:
        - Crear usuario
      operationId: crearUsuario
      requestBody:
        description: Crear usuario
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsuarioTypeInput"
      responses:
        "200":
          description: Usuario creado.
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/UsuarioTypeResponse"
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra la novedad."
#GET - LISTAR USUARIO
  /v1/es/listUsuario/{idtbl_user}:
    get:
      tags:
        - Listar usuario
      parameters:
        - in: path
          name: idtbl_user   # Note the name is the same as in the path
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      operationId: listarUsuario
      responses:
        "200":
          description: Usuario creado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UsuarioTypeResponse"
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra la novedad."
#DELETE - ELIMINAR USUARIO
  /v1/es/deleteUsuario/{idtbl_user}:
    delete:
      tags:
        - Eliminar usuario
      parameters:
        - in: path
          name: idtbl_user
      operationId: eliminarUsuario
      requestBody:
        description: Eliminar usuario
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsuarioTypeInput"
      responses:
        "200":
          description: Usuario Eliminado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsuarioTypeResponse"
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra la novedad."
#PUT - ACTUALIZAR USUARIO
  /v1/es/updateUsuario/{idtbl_user}:
    put:
      tags:
        - Actualizar usuario
      parameters:
        - in: path
          name: idtbl_user
      operationId: actualizarUsuario
      requestBody:
        description: Actualizar usuario
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsuarioTypeInput"
      responses:
        "200":
          description: Usuario Actualizado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsuarioTypeResponse"
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra la novedad."

#---------------------------------------------

#Se declaran los Modelos/Schemas del servicio

#---------------------------------------------

components:

  schemas:

    UsuarioTypeResponse:

      type: object

      properties:

        name:

          type: string

        lastname:

          type: string

    UsuarioTypeInput:

      type: object

      properties:

        name:

          type: string

        lastname:

          type: string